 CREATE TABLE categories (
     id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
     category_name VARCHAR(255) NOT NULL,
     createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
 );